language: ruby
rvm:
  - 1.9.3
script: bundle rake rspec twitter_analysis/spec
services: 
  -mongodb
before_script:
  - psql -c 'create database test-postgres_production;' -U test-postgres
gemfile:
  - /twitter_analysis/Gemfile