language: ruby
rvm:
  - 1.9.3
script: bundle rake rspec spec
services: 
  -mongodb
gemfile:
  - Gemfile
env:
  - DB=postgresql
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
before_script:
  - bundle exec rake db:create RAILS_ENV=test
services:
  - mongodb